'use strict';
// Reference data for the demo seed: realistic Indian hospital masters.

const DEPARTMENTS = [
  ['General Medicine', 'GM', 'clinical'], ['Cardiology', 'CAR', 'clinical'], ['Orthopedics', 'ORT', 'clinical'], ['Pediatrics', 'PED', 'clinical'],
  ['Dermatology', 'DER', 'clinical'], ['Gynecology', 'GYN', 'clinical'], ['ENT', 'ENT', 'clinical'], ['Emergency', 'EMR', 'clinical'],
  ['Pharmacy', 'PHA', 'support'], ['Laboratory', 'LAB', 'support'], ['Radiology', 'RAD', 'support'], ['Nursing', 'NUR', 'support'],
  ['Housekeeping', 'HK', 'support'], ['Administration', 'ADM', 'admin'], ['Accounts', 'ACC', 'admin'], ['Human Resources', 'HR', 'admin'],
];

// [name, department, specialization, qualification, fee, followup fee, prefix, room, username]
const DOCTORS = [
  ['Dr. Rajesh Mehta', 'General Medicine', 'Internal Medicine', 'MBBS, MD (Medicine)', 600, 300, 'A', 'OPD Room 1', 'dr.mehta'],
  ['Dr. Nidhi Shah', 'Cardiology', 'Interventional Cardiology', 'MBBS, MD, DM (Cardiology)', 1000, 500, 'B', 'OPD Room 4', 'dr.shah'],
  ['Dr. Kunal Patel', 'Orthopedics', 'Joint Replacement', 'MBBS, MS (Ortho)', 800, 400, 'C', 'OPD Room 6', 'dr.patel'],
  ['Dr. Ananya Desai', 'Pediatrics', 'Neonatology', 'MBBS, MD (Pediatrics)', 700, 350, 'D', 'OPD Room 3', 'dr.desai'],
  ['Dr. Vikram Joshi', 'Dermatology', 'Clinical Dermatology', 'MBBS, MD (DVL)', 700, 350, 'E', 'OPD Room 7', 'dr.joshi'],
  ['Dr. Meera Trivedi', 'Gynecology', 'Obstetrics & Gynecology', 'MBBS, MS (OBG)', 800, 400, 'F', 'OPD Room 5', 'dr.trivedi'],
  ['Dr. Harsh Parikh', 'ENT', 'Otorhinolaryngology', 'MBBS, MS (ENT)', 700, 350, 'G', 'OPD Room 8', 'dr.parikh'],
  ['Dr. Sameer Bhatt', 'General Medicine', 'Diabetology', 'MBBS, MD (Medicine)', 600, 300, 'H', 'OPD Room 2', 'dr.bhatt'],
];

// [code, name, specialty, common, synonyms]
const DIAGNOSES = [
  ['R50.9', 'Fever, unspecified', 'General Medicine', 1, 'pyrexia, fever'],
  ['J06.9', 'Acute upper respiratory infection (URTI)', 'General Medicine', 1, 'urti, common cold, cold, cough'],
  ['I10', 'Essential (primary) hypertension', 'Cardiology', 1, 'htn, high blood pressure, hypertension'],
  ['E11.9', 'Type 2 diabetes mellitus without complications', 'General Medicine', 1, 'dm, t2dm, diabetes, sugar'],
  ['K29.1', 'Acute gastritis', 'General Medicine', 1, 'gastritis, acidity, dyspepsia'],
  ['K21.9', 'Gastro-oesophageal reflux disease', 'General Medicine', 1, 'gerd, reflux, heartburn'],
  ['A09', 'Acute gastroenteritis', 'General Medicine', 1, 'age, diarrhoea, loose motions, vomiting'],
  ['J02.9', 'Acute pharyngitis', 'ENT', 1, 'sore throat, pharyngitis'],
  ['J03.90', 'Acute tonsillitis', 'ENT', 1, 'tonsillitis'],
  ['J30.4', 'Allergic rhinitis', 'ENT', 1, 'rhinitis, allergy, sneezing'],
  ['H66.9', 'Otitis media', 'ENT', 0, 'ear infection, ear pain, om'],
  ['J32.9', 'Chronic sinusitis', 'ENT', 0, 'sinusitis'],
  ['J20.9', 'Acute bronchitis', 'General Medicine', 1, 'bronchitis, cough'],
  ['J45.909', 'Bronchial asthma', 'General Medicine', 0, 'asthma, wheeze'],
  ['J18.9', 'Pneumonia, unspecified', 'General Medicine', 0, 'pneumonia, lrti'],
  ['A90', 'Dengue fever', 'General Medicine', 0, 'dengue'],
  ['B54', 'Malaria, unspecified', 'General Medicine', 0, 'malaria'],
  ['A01.0', 'Typhoid fever', 'General Medicine', 0, 'enteric fever, typhoid'],
  ['N39.0', 'Urinary tract infection', 'General Medicine', 1, 'uti, burning micturition'],
  ['E78.5', 'Dyslipidaemia', 'Cardiology', 0, 'hyperlipidemia, cholesterol'],
  ['I25.10', 'Coronary artery disease', 'Cardiology', 0, 'cad, ihd'],
  ['I20.9', 'Angina pectoris', 'Cardiology', 0, 'chest pain, angina'],
  ['I48.91', 'Atrial fibrillation', 'Cardiology', 0, 'af, afib'],
  ['I50.9', 'Heart failure', 'Cardiology', 0, 'chf, ccf'],
  ['R07.9', 'Chest pain, unspecified', 'Cardiology', 0, 'chest pain'],
  ['E03.9', 'Hypothyroidism', 'General Medicine', 1, 'thyroid, hypothyroid'],
  ['D64.9', 'Anaemia, unspecified', 'General Medicine', 1, 'anemia, low hb'],
  ['E55.9', 'Vitamin D deficiency', 'General Medicine', 0, 'vit d'],
  ['R51', 'Headache', 'General Medicine', 1, 'headache'],
  ['G43.909', 'Migraine', 'General Medicine', 0, 'migraine'],
  ['F41.9', 'Anxiety disorder', 'General Medicine', 0, 'anxiety'],
  ['M54.5', 'Low back pain', 'Orthopedics', 1, 'lbp, backache, back pain'],
  ['M17.9', 'Osteoarthritis of knee', 'Orthopedics', 1, 'oa knee, knee pain'],
  ['M75.0', 'Adhesive capsulitis of shoulder', 'Orthopedics', 0, 'frozen shoulder'],
  ['M54.2', 'Cervicalgia', 'Orthopedics', 1, 'neck pain, cervical spondylosis'],
  ['S93.40', 'Sprain of ankle', 'Orthopedics', 1, 'ankle sprain'],
  ['S52.50', 'Fracture of lower end of radius', 'Orthopedics', 0, 'colles fracture, wrist fracture'],
  ['M81.0', 'Osteoporosis', 'Orthopedics', 0, 'osteoporosis'],
  ['M79.1', 'Myalgia', 'Orthopedics', 0, 'body ache, muscle pain'],
  ['L70.0', 'Acne vulgaris', 'Dermatology', 1, 'acne, pimples'],
  ['L20.9', 'Atopic dermatitis', 'Dermatology', 0, 'eczema'],
  ['B35.4', 'Tinea corporis', 'Dermatology', 1, 'ringworm, fungal infection'],
  ['L50.9', 'Urticaria', 'Dermatology', 1, 'hives, urticaria, itching'],
  ['L40.0', 'Psoriasis vulgaris', 'Dermatology', 0, 'psoriasis'],
  ['B86', 'Scabies', 'Dermatology', 0, 'scabies'],
  ['L21.9', 'Seborrhoeic dermatitis', 'Dermatology', 0, 'dandruff'],
  ['N94.6', 'Dysmenorrhoea', 'Gynecology', 1, 'painful periods'],
  ['E28.2', 'Polycystic ovarian syndrome', 'Gynecology', 1, 'pcos, pcod'],
  ['Z34.90', 'Supervision of normal pregnancy', 'Gynecology', 1, 'anc, pregnancy'],
  ['N76.0', 'Acute vaginitis', 'Gynecology', 0, 'vaginitis'],
  ['N92.0', 'Menorrhagia', 'Gynecology', 0, 'heavy periods'],
  ['O21.0', 'Hyperemesis gravidarum (mild)', 'Gynecology', 0, 'vomiting in pregnancy'],
  ['A08.4', 'Viral gastroenteritis (child)', 'Pediatrics', 1, 'loose motions child'],
  ['J21.9', 'Acute bronchiolitis', 'Pediatrics', 0, 'bronchiolitis'],
  ['R62.50', 'Failure to thrive', 'Pediatrics', 0, 'poor weight gain'],
  ['Z00.129', 'Routine child health examination', 'Pediatrics', 1, 'well baby, vaccination visit'],
  ['P59.9', 'Neonatal jaundice', 'Pediatrics', 0, 'jaundice newborn'],
  ['B01.9', 'Varicella (chickenpox)', 'Pediatrics', 0, 'chickenpox'],
  ['H10.9', 'Conjunctivitis', 'General Medicine', 0, 'conjunctivitis, red eye'],
  ['K59.00', 'Constipation', 'General Medicine', 0, 'constipation'],
  ['K80.20', 'Cholelithiasis', 'General Medicine', 0, 'gall stones'],
  ['N20.0', 'Renal calculus', 'General Medicine', 0, 'kidney stone'],
  ['R42', 'Vertigo / dizziness', 'ENT', 0, 'giddiness, vertigo'],
  ['T78.40', 'Allergic reaction', 'General Medicine', 0, 'allergy'],
  ['S01.80', 'Laceration / open wound', 'Emergency', 0, 'cut, wound'],
  ['T14.90', 'Injury, unspecified', 'Emergency', 0, 'trauma, injury'],
  ['R55', 'Syncope', 'Emergency', 0, 'fainting, syncope'],
  ['I63.9', 'Cerebral infarction (stroke)', 'Emergency', 0, 'stroke, cva'],
  ['E86.0', 'Dehydration', 'Emergency', 0, 'dehydration'],
];

// [name, generic, brand, strength, form, manufacturer, category, purchase, selling, min stock, route, gst, hsn]
const MEDICINES = [
  ['Paracetamol', 'Paracetamol', 'Dolo 650', '650 mg', 'Tablet', 'Micro Labs', 'Analgesic / Antipyretic', 1.6, 2.1, 400, 'Oral', 12, '3004'],
  ['Paracetamol Syrup', 'Paracetamol', 'Calpol', '250 mg/5 ml', 'Syrup', 'GSK', 'Analgesic / Antipyretic', 38, 52, 40, 'Oral', 12, '3004'],
  ['Pantoprazole', 'Pantoprazole', 'Pan 40', '40 mg', 'Tablet', 'Alkem', 'Antacid / PPI', 6.5, 9.8, 300, 'Oral', 12, '3004'],
  ['Rabeprazole + Domperidone', 'Rabeprazole + Domperidone', 'Rablet-D', '20/30 mg', 'Capsule', 'Lupin', 'Antacid / PPI', 7.2, 11.5, 200, 'Oral', 12, '3004'],
  ['Domperidone', 'Domperidone', 'Domstal', '10 mg', 'Tablet', 'Torrent', 'Antiemetic', 2.2, 3.4, 150, 'Oral', 12, '3004'],
  ['Ondansetron', 'Ondansetron', 'Emeset', '4 mg', 'Tablet', 'Cipla', 'Antiemetic', 3.5, 5.6, 150, 'Oral', 12, '3004'],
  ['Antacid Gel', 'Magaldrate + Simethicone', 'Digene', '200 ml', 'Suspension', 'Abbott', 'Antacid / PPI', 95, 128, 30, 'Oral', 12, '3004'],
  ['ORS', 'Oral rehydration salts', 'Electral', '21.8 g', 'Sachet', 'FDC', 'Electrolyte', 16, 22, 200, 'Oral', 12, '3004'],
  ['Racecadotril', 'Racecadotril', 'Redotil', '100 mg', 'Capsule', "Dr. Reddy's", 'Antidiarrhoeal', 12, 17.5, 60, 'Oral', 12, '3004'],
  ['Amoxicillin + Clavulanate', 'Amoxicillin + Clavulanic acid', 'Augmentin 625 Duo', '625 mg', 'Tablet', 'GSK', 'Antibiotic', 15.5, 22.3, 200, 'Oral', 12, '3004'],
  ['Azithromycin', 'Azithromycin', 'Azithral 500', '500 mg', 'Tablet', 'Alembic', 'Antibiotic', 17, 24.5, 150, 'Oral', 12, '3004'],
  ['Cefixime', 'Cefixime', 'Taxim-O', '200 mg', 'Tablet', 'Alkem', 'Antibiotic', 9.5, 13.9, 150, 'Oral', 12, '3004'],
  ['Nitrofurantoin', 'Nitrofurantoin', 'Niftran', '100 mg', 'Capsule', 'Ranbaxy', 'Antibiotic', 6.8, 9.9, 80, 'Oral', 12, '3004'],
  ['Ciprofloxacin', 'Ciprofloxacin', 'Ciplox 500', '500 mg', 'Tablet', 'Cipla', 'Antibiotic', 3.2, 4.8, 100, 'Oral', 12, '3004'],
  ['Cetirizine', 'Cetirizine', 'Cetzine', '10 mg', 'Tablet', 'GSK', 'Antihistamine', 1.2, 1.9, 250, 'Oral', 12, '3004'],
  ['Levocetirizine', 'Levocetirizine', 'Levocet', '5 mg', 'Tablet', 'Hetero', 'Antihistamine', 2.1, 3.2, 200, 'Oral', 12, '3004'],
  ['Montelukast + Levocetirizine', 'Montelukast + Levocetirizine', 'Montair-LC', '10/5 mg', 'Tablet', 'Cipla', 'Antihistamine', 9.8, 14.5, 150, 'Oral', 12, '3004'],
  ['Fluticasone Nasal Spray', 'Fluticasone propionate', 'Flutiflo', '50 mcg', 'Nasal spray', 'Cipla', 'Nasal steroid', 180, 245, 20, 'Nasal', 12, '3004'],
  ['Cough Syrup', 'Dextromethorphan + Chlorpheniramine', 'Ascoril D', '100 ml', 'Syrup', 'Glenmark', 'Antitussive', 78, 112, 40, 'Oral', 12, '3004'],
  ['Amlodipine', 'Amlodipine', 'Amlong 5', '5 mg', 'Tablet', 'Micro Labs', 'Antihypertensive', 1.8, 2.9, 300, 'Oral', 12, '3004'],
  ['Telmisartan', 'Telmisartan', 'Telma 40', '40 mg', 'Tablet', 'Glenmark', 'Antihypertensive', 7.5, 11.2, 250, 'Oral', 12, '3004'],
  ['Metoprolol', 'Metoprolol succinate', 'Metolar XR 25', '25 mg', 'Tablet', 'Cipla', 'Beta blocker', 4.6, 6.9, 150, 'Oral', 12, '3004'],
  ['Atorvastatin', 'Atorvastatin', 'Atorva 10', '10 mg', 'Tablet', 'Zydus', 'Statin', 5.2, 7.9, 250, 'Oral', 12, '3004'],
  ['Aspirin', 'Aspirin', 'Ecosprin 75', '75 mg', 'Tablet', 'USV', 'Antiplatelet', 0.4, 0.6, 300, 'Oral', 12, '3004'],
  ['Clopidogrel', 'Clopidogrel', 'Clopilet 75', '75 mg', 'Tablet', 'Sun Pharma', 'Antiplatelet', 4.8, 7.4, 120, 'Oral', 12, '3004'],
  ['Metformin', 'Metformin', 'Glycomet 500', '500 mg', 'Tablet', 'USV', 'Antidiabetic', 1.2, 1.9, 400, 'Oral', 12, '3004'],
  ['Glimepiride', 'Glimepiride', 'Amaryl 1', '1 mg', 'Tablet', 'Sanofi', 'Antidiabetic', 5.9, 8.8, 150, 'Oral', 12, '3004'],
  ['Sitagliptin + Metformin', 'Sitagliptin + Metformin', 'Istamet 50/500', '50/500 mg', 'Tablet', 'MSD', 'Antidiabetic', 16, 23.5, 100, 'Oral', 12, '3004'],
  ['Levothyroxine', 'Levothyroxine', 'Thyronorm 50', '50 mcg', 'Tablet', 'Abbott', 'Thyroid', 1.3, 1.9, 200, 'Oral', 12, '3004'],
  ['Aceclofenac + Paracetamol', 'Aceclofenac + Paracetamol', 'Zerodol-P', '100/325 mg', 'Tablet', 'Ipca', 'NSAID', 3.9, 5.9, 250, 'Oral', 12, '3004'],
  ['Thiocolchicoside', 'Thiocolchicoside', 'Myoril 4', '4 mg', 'Capsule', 'Sun Pharma', 'Muscle relaxant', 11, 16.2, 100, 'Oral', 12, '3004'],
  ['Diclofenac Gel', 'Diclofenac diethylamine', 'Volini', '30 g', 'Gel', 'Sun Pharma', 'NSAID', 88, 125, 30, 'Topical', 12, '3004'],
  ['Calcium + Vitamin D3', 'Calcium carbonate + Cholecalciferol', 'Shelcal 500', '500 mg', 'Tablet', 'Torrent', 'Supplement', 4.5, 6.8, 300, 'Oral', 12, '3004'],
  ['Vitamin D3', 'Cholecalciferol', 'Uprise D3 60K', '60000 IU', 'Capsule', 'Alkem', 'Supplement', 22, 31, 60, 'Oral', 12, '3004'],
  ['Iron + Folic Acid', 'Ferrous ascorbate + Folic acid', 'Orofer XT', '100 mg', 'Tablet', 'Emcure', 'Supplement', 10.2, 15.2, 200, 'Oral', 12, '3004'],
  ['Clindamycin Gel', 'Clindamycin phosphate', 'Clindac A', '15 g', 'Gel', 'Galderma', 'Topical antibiotic', 95, 138, 25, 'Topical', 12, '3004'],
  ['Adapalene Gel', 'Adapalene', 'Adaferin', '15 g', 'Gel', 'Galderma', 'Topical retinoid', 185, 260, 20, 'Topical', 12, '3004'],
  ['Luliconazole Cream', 'Luliconazole', 'Lulifin', '30 g', 'Cream', 'Sun Pharma', 'Antifungal', 210, 295, 25, 'Topical', 12, '3004'],
  ['Terbinafine', 'Terbinafine', 'Terbicip 250', '250 mg', 'Tablet', 'Cipla', 'Antifungal', 13, 19.5, 80, 'Oral', 12, '3004'],
  ['Mefenamic Acid', 'Mefenamic acid + Dicyclomine', 'Meftal Spas', '250/10 mg', 'Tablet', 'Blue Cross', 'Antispasmodic', 3.1, 4.7, 150, 'Oral', 12, '3004'],
  ['Folic Acid', 'Folic acid', 'Folvite 5', '5 mg', 'Tablet', 'Pfizer', 'Supplement', 1.1, 1.7, 200, 'Oral', 12, '3004'],
  ['Salbutamol Inhaler', 'Salbutamol', 'Asthalin', '100 mcg', 'Inhaler', 'Cipla', 'Bronchodilator', 105, 148, 20, 'Inhalation', 12, '3004'],
  ['Ceftriaxone Injection', 'Ceftriaxone', 'Monocef 1g', '1 g', 'Injection', 'Aristo', 'Antibiotic', 42, 62, 60, 'IV', 12, '3004'],
  ['Normal Saline', 'Sodium chloride 0.9%', 'NS 500', '500 ml', 'IV fluid', 'Baxter', 'IV fluid', 24, 34, 100, 'IV', 12, '3004'],
  ['Ringer Lactate', 'Ringer lactate', 'RL 500', '500 ml', 'IV fluid', 'Baxter', 'IV fluid', 28, 39, 80, 'IV', 12, '3004'],
  ['Pantoprazole Injection', 'Pantoprazole', 'Pan IV', '40 mg', 'Injection', 'Alkem', 'Antacid / PPI', 38, 55, 50, 'IV', 12, '3004'],
  ['Ondansetron Injection', 'Ondansetron', 'Emeset Inj', '2 mg/ml', 'Injection', 'Cipla', 'Antiemetic', 9, 14, 50, 'IV', 12, '3004'],
  ['Insulin Glargine', 'Insulin glargine', 'Basalog', '100 IU/ml', 'Injection', 'Biocon', 'Antidiabetic', 520, 710, 10, 'SC', 5, '3004'],
  ['Enoxaparin', 'Enoxaparin', 'Clexane 40', '40 mg', 'Injection', 'Sanofi', 'Anticoagulant', 285, 385, 15, 'SC', 12, '3004'],
  ['Multivitamin', 'Multivitamin + Minerals', 'Becosules', '—', 'Capsule', 'Pfizer', 'Supplement', 1.9, 2.8, 200, 'Oral', 12, '3004'],
];

// Templates: diagnosis name → [medicine name, dose, frequency, days, route, instructions]
const TEMPLATES = [
  ['Acute gastritis', 'Acute gastritis — standard', 'Avoid spicy/oily food, small frequent meals, no NSAIDs.', [['Pantoprazole', '1 tab', 'OD', 5, 'Oral', 'Before breakfast'], ['Domperidone', '1 tab', 'TDS', 5, 'Oral', '15 min before meals'], ['Antacid Gel', '10 ml', 'TDS', 5, 'Oral', 'After meals']]],
  ['Fever, unspecified', 'Fever — symptomatic', 'Plenty of oral fluids, tepid sponging, review if fever > 3 days.', [['Paracetamol', '1 tab', 'TDS', 3, 'Oral', 'After food, if temp > 100°F']]],
  ['Acute upper respiratory infection (URTI)', 'URTI — adult', 'Steam inhalation, warm saline gargles.', [['Paracetamol', '1 tab', 'TDS', 3, 'Oral', 'After food'], ['Cetirizine', '1 tab', 'HS', 5, 'Oral', 'At bedtime'], ['Cough Syrup', '10 ml', 'TDS', 5, 'Oral', '']]],
  ['Essential (primary) hypertension', 'Hypertension — initiation', 'Salt restriction < 5 g/day, daily walk 30 min, home BP log.', [['Amlodipine', '1 tab', 'OD', 30, 'Oral', 'Morning']]],
  ['Type 2 diabetes mellitus without complications', 'T2DM — initiation', 'Diabetic diet, HbA1c after 3 months.', [['Metformin', '1 tab', 'BD', 30, 'Oral', 'After meals']]],
  ['Acute gastroenteritis', 'AGE — adult', 'ORS after every loose stool, light diet.', [['ORS', '1 sachet', 'TDS', 3, 'Oral', 'Dissolve in 1 L water'], ['Ondansetron', '1 tab', 'SOS', 3, 'Oral', 'If vomiting'], ['Racecadotril', '1 cap', 'TDS', 3, 'Oral', '']]],
  ['Allergic rhinitis', 'Allergic rhinitis', 'Avoid dust exposure.', [['Montelukast + Levocetirizine', '1 tab', 'HS', 10, 'Oral', 'At bedtime'], ['Fluticasone Nasal Spray', '2 puffs', 'OD', 14, 'Nasal', 'Each nostril']]],
  ['Low back pain', 'Mechanical low back pain', 'Hot fomentation, back extension exercises, avoid lifting.', [['Aceclofenac + Paracetamol', '1 tab', 'BD', 5, 'Oral', 'After food'], ['Thiocolchicoside', '1 cap', 'BD', 5, 'Oral', ''], ['Pantoprazole', '1 tab', 'OD', 5, 'Oral', 'Before breakfast']]],
  ['Acne vulgaris', 'Acne — mild/moderate', 'Gentle face wash twice daily, avoid oily cosmetics.', [['Clindamycin Gel', 'Thin layer', 'OD', 30, 'Topical', 'Morning'], ['Adapalene Gel', 'Pea size', 'HS', 30, 'Topical', 'Night, avoid sun']]],
  ['Urinary tract infection', 'Uncomplicated UTI', 'Increase water intake to 3 L/day. Urine culture if recurrent.', [['Nitrofurantoin', '1 cap', 'BD', 5, 'Oral', 'After food'], ['Paracetamol', '1 tab', 'SOS', 3, 'Oral', 'For pain/fever']]],
  ['Tinea corporis', 'Tinea corporis', 'Keep area dry, loose cotton clothing, wash clothes in hot water.', [['Luliconazole Cream', 'Apply', 'OD', 21, 'Topical', 'Beyond margins'], ['Levocetirizine', '1 tab', 'HS', 10, 'Oral', 'For itching']]],
  ['Osteoarthritis of knee', 'OA knee', 'Quadriceps strengthening, weight reduction.', [['Aceclofenac + Paracetamol', '1 tab', 'BD', 7, 'Oral', 'After food'], ['Calcium + Vitamin D3', '1 tab', 'OD', 30, 'Oral', 'After lunch'], ['Diclofenac Gel', 'Apply', 'TDS', 14, 'Topical', 'Local application']]],
  ['Dysmenorrhoea', 'Primary dysmenorrhoea', 'Warm compress, review if severe.', [['Mefenamic Acid', '1 tab', 'TDS', 3, 'Oral', 'After food, during periods']]],
  ['Hypothyroidism', 'Hypothyroidism', 'TSH after 6 weeks.', [['Levothyroxine', '1 tab', 'OD', 30, 'Oral', 'Empty stomach, 30 min before breakfast']]],
  ['Anaemia, unspecified', 'Iron deficiency anaemia', 'Iron-rich diet, CBC after 4 weeks.', [['Iron + Folic Acid', '1 tab', 'OD', 30, 'Oral', 'After lunch'], ['Multivitamin', '1 cap', 'OD', 30, 'Oral', '']]],
  ['Acute pharyngitis', 'Acute pharyngitis', 'Warm saline gargles.', [['Azithromycin', '1 tab', 'OD', 3, 'Oral', '1 hr before food'], ['Paracetamol', '1 tab', 'TDS', 3, 'Oral', 'After food']]],
];

// [code, name, category, sample, price, TAT h, parameters]
const LAB_TESTS = [
  ['CBC', 'Complete Blood Count', 'Haematology', 'EDTA blood', 350, 6, [{ name: 'Haemoglobin', unit: 'g/dL', ref_low: 12, ref_high: 16.5, critical_low: 7 }, { name: 'Total WBC count', unit: '/µL', ref_low: 4000, ref_high: 11000 }, { name: 'Platelet count', unit: 'lakh/µL', ref_low: 1.5, ref_high: 4.5, critical_low: 0.5 }, { name: 'RBC count', unit: 'million/µL', ref_low: 4.2, ref_high: 5.9 }, { name: 'PCV', unit: '%', ref_low: 36, ref_high: 50 }]],
  ['FBS', 'Blood Sugar — Fasting', 'Biochemistry', 'Fluoride plasma', 80, 2, [{ name: 'Fasting glucose', unit: 'mg/dL', ref_low: 70, ref_high: 100, critical_low: 50, critical_high: 400 }]],
  ['PPBS', 'Blood Sugar — Post Prandial', 'Biochemistry', 'Fluoride plasma', 80, 2, [{ name: 'PP glucose', unit: 'mg/dL', ref_low: 70, ref_high: 140, critical_high: 450 }]],
  ['HBA1C', 'HbA1c (Glycated Haemoglobin)', 'Biochemistry', 'EDTA blood', 550, 12, [{ name: 'HbA1c', unit: '%', ref_low: 4, ref_high: 5.6 }]],
  ['LIPID', 'Lipid Profile', 'Biochemistry', 'Serum', 600, 12, [{ name: 'Total cholesterol', unit: 'mg/dL', ref_low: 0, ref_high: 200 }, { name: 'Triglycerides', unit: 'mg/dL', ref_low: 0, ref_high: 150 }, { name: 'HDL', unit: 'mg/dL', ref_low: 40, ref_high: 100 }, { name: 'LDL', unit: 'mg/dL', ref_low: 0, ref_high: 130 }]],
  ['LFT', 'Liver Function Test', 'Biochemistry', 'Serum', 700, 12, [{ name: 'Total bilirubin', unit: 'mg/dL', ref_low: 0.2, ref_high: 1.2 }, { name: 'SGOT (AST)', unit: 'U/L', ref_low: 5, ref_high: 40 }, { name: 'SGPT (ALT)', unit: 'U/L', ref_low: 5, ref_high: 41 }, { name: 'Alkaline phosphatase', unit: 'U/L', ref_low: 40, ref_high: 130 }, { name: 'Albumin', unit: 'g/dL', ref_low: 3.5, ref_high: 5.2 }]],
  ['KFT', 'Kidney Function Test', 'Biochemistry', 'Serum', 650, 12, [{ name: 'Blood urea', unit: 'mg/dL', ref_low: 15, ref_high: 45 }, { name: 'Serum creatinine', unit: 'mg/dL', ref_low: 0.6, ref_high: 1.3, critical_high: 5 }, { name: 'Uric acid', unit: 'mg/dL', ref_low: 3.5, ref_high: 7.2 }]],
  ['ELEC', 'Serum Electrolytes', 'Biochemistry', 'Serum', 450, 6, [{ name: 'Sodium', unit: 'mmol/L', ref_low: 135, ref_high: 145, critical_low: 120, critical_high: 160 }, { name: 'Potassium', unit: 'mmol/L', ref_low: 3.5, ref_high: 5.1, critical_low: 2.5, critical_high: 6.5 }, { name: 'Chloride', unit: 'mmol/L', ref_low: 98, ref_high: 107 }]],
  ['TSH', 'Thyroid Stimulating Hormone', 'Immunoassay', 'Serum', 400, 24, [{ name: 'TSH', unit: 'µIU/mL', ref_low: 0.4, ref_high: 4.5 }]],
  ['CRP', 'C-Reactive Protein', 'Immunology', 'Serum', 450, 6, [{ name: 'CRP', unit: 'mg/L', ref_low: 0, ref_high: 6 }]],
  ['URINE', 'Urine Routine & Microscopy', 'Clinical Pathology', 'Urine', 150, 4, [{ name: 'Pus cells', unit: '/hpf', ref_low: 0, ref_high: 5 }, { name: 'RBCs', unit: '/hpf', ref_low: 0, ref_high: 2 }, { name: 'Protein', unit: '', ref_text: 'Nil' }, { name: 'Sugar', unit: '', ref_text: 'Nil' }]],
  ['NS1', 'Dengue NS1 Antigen', 'Serology', 'Serum', 600, 6, [{ name: 'Dengue NS1', unit: '', ref_text: 'Negative' }]],
  ['WIDAL', 'Widal Test', 'Serology', 'Serum', 250, 6, [{ name: 'S. Typhi O', unit: 'titre', ref_text: '< 1:80' }, { name: 'S. Typhi H', unit: 'titre', ref_text: '< 1:160' }]],
  ['MP', 'Malaria Parasite (Rapid)', 'Serology', 'EDTA blood', 300, 2, [{ name: 'P. vivax', unit: '', ref_text: 'Negative' }, { name: 'P. falciparum', unit: '', ref_text: 'Negative' }]],
  ['VITD', 'Vitamin D (25-OH)', 'Immunoassay', 'Serum', 1200, 24, [{ name: '25-OH Vitamin D', unit: 'ng/mL', ref_low: 30, ref_high: 100 }]],
  ['B12', 'Vitamin B12', 'Immunoassay', 'Serum', 900, 24, [{ name: 'Vitamin B12', unit: 'pg/mL', ref_low: 211, ref_high: 911 }]],
];

const WARDS = [
  ['ICU', 'icu', '2nd Floor', 12000, 8, 'ICU'], ['NICU', 'nicu', '2nd Floor', 10000, 4, 'NICU'], ['Emergency Observation', 'emergency', 'Ground', 2500, 4, 'ER'],
  ['General Ward — Male', 'general', '1st Floor', 1500, 12, 'GM'], ['General Ward — Female', 'general', '1st Floor', 1500, 12, 'GF'],
  ['Semi-Private', 'semi_private', '3rd Floor', 3000, 8, 'SP'], ['Private Rooms', 'private', '4th Floor', 5500, 6, 'PR'],
];

const SUPPLIERS = [
  ['Gujarat Pharma Distributors', 'Mahesh Thakkar', '9824012345', 'orders@gujaratpharma.in', 'Ashram Road, Ahmedabad', '24AABCG1234F1Z5'],
  ['Shree Medicare Agencies', 'Pooja Soni', '9898056789', 'sales@shreemedicare.in', 'Navrangpura, Ahmedabad', '24AAFCS5678K1Z2'],
  ['Sanjeevani Surgicals', 'Rakesh Vora', '9727011122', 'info@sanjeevanisurgicals.in', 'Maninagar, Ahmedabad', '24AAKCS9012L1Z8'],
  ['MedEquip India Pvt Ltd', 'Anil Kapoor', '9811022233', 'support@medequipindia.in', 'Andheri East, Mumbai', '27AAACM3456P1Z1'],
];

const INVENTORY_ITEMS = [
  ['EQ-001', 'Multipara Patient Monitor', 'equipment', 'pcs', 14, 2, 85000], ['EQ-002', 'Infusion Pump', 'equipment', 'pcs', 18, 4, 42000], ['EQ-003', 'Pulse Oximeter (Fingertip)', 'equipment', 'pcs', 25, 10, 1800],
  ['EQ-004', 'Digital BP Monitor', 'equipment', 'pcs', 12, 5, 2400], ['EQ-005', 'Nebulizer Machine', 'equipment', 'pcs', 6, 3, 3200], ['EQ-006', 'Glucometer', 'equipment', 'pcs', 9, 5, 1100],
  ['CN-001', 'Disposable Syringe 5 ml', 'consumable', 'pcs', 1800, 1000, 4.5], ['CN-002', 'IV Cannula 20G', 'consumable', 'pcs', 420, 300, 28], ['CN-003', 'Examination Gloves (M)', 'consumable', 'box', 60, 40, 320],
  ['CN-004', 'Surgical Mask 3-ply', 'consumable', 'box', 18, 30, 150], ['CN-005', 'Glucometer Strips', 'consumable', 'box', 35, 20, 650], ['CN-006', 'Cotton Roll 500 g', 'consumable', 'pcs', 70, 40, 180],
  ['SU-001', 'Sterile Surgical Gloves 7.0', 'surgical', 'pair', 260, 200, 38], ['SU-002', 'Suture Nylon 3-0', 'surgical', 'pcs', 90, 60, 95], ['SU-003', 'Surgical Blade No. 22', 'surgical', 'pcs', 300, 150, 7],
  ['GN-001', 'Bed Sheet (White)', 'general', 'pcs', 240, 150, 260], ['GN-002', 'Patient Gown', 'general', 'pcs', 110, 120, 340], ['GN-003', 'Printer Paper A4', 'general', 'ream', 25, 15, 290],
];

const FIRST = { Male: ['Rahul', 'Amit', 'Rohan', 'Vivek', 'Karan', 'Nikhil', 'Harsh', 'Mihir', 'Parth', 'Jay', 'Dhruv', 'Yash', 'Chirag', 'Hardik', 'Kishan', 'Ramesh', 'Suresh', 'Mahesh', 'Bhavesh', 'Jignesh', 'Kalpesh', 'Nirav', 'Sanjay', 'Arjun', 'Aarav', 'Vihaan', 'Ishaan', 'Manoj', 'Dinesh', 'Prakash', 'Hitesh', 'Tushar', 'Ankit', 'Deepak', 'Mohit'],
  Female: ['Priya', 'Neha', 'Pooja', 'Riya', 'Kavya', 'Anjali', 'Hetal', 'Krupa', 'Nisha', 'Shreya', 'Dhara', 'Jinal', 'Khushi', 'Mansi', 'Payal', 'Rekha', 'Sunita', 'Geeta', 'Bhavna', 'Komal', 'Falguni', 'Hema', 'Asha', 'Isha', 'Diya', 'Aanya', 'Saanvi', 'Meena', 'Kiran', 'Sejal', 'Urvi', 'Nidhi', 'Rupal', 'Varsha', 'Trupti'] };
const LAST = ['Shah', 'Patel', 'Desai', 'Mehta', 'Joshi', 'Trivedi', 'Parikh', 'Bhatt', 'Pandya', 'Dave', 'Modi', 'Thakkar', 'Vyas', 'Chauhan', 'Solanki', 'Rathod', 'Parmar', 'Gandhi', 'Kapadia', 'Sheth', 'Amin', 'Soni', 'Panchal', 'Prajapati', 'Raval', 'Chaudhary', 'Iyer', 'Nair', 'Sharma', 'Verma', 'Gupta', 'Agarwal', 'Rao', 'Kulkarni', 'Jain'];
const AREAS = [['Navrangpura', 'Ahmedabad', '380009'], ['Satellite', 'Ahmedabad', '380015'], ['Bopal', 'Ahmedabad', '380058'], ['Maninagar', 'Ahmedabad', '380008'], ['Vastrapur', 'Ahmedabad', '380015'], ['Paldi', 'Ahmedabad', '380007'], ['Chandkheda', 'Ahmedabad', '382424'], ['Naranpura', 'Ahmedabad', '380013'], ['Thaltej', 'Ahmedabad', '380059'], ['Gota', 'Ahmedabad', '382481'], ['Nikol', 'Ahmedabad', '382350'], ['Gandhinagar Sec 21', 'Gandhinagar', '382021'], ['Sabarmati', 'Ahmedabad', '380005'], ['Prahlad Nagar', 'Ahmedabad', '380015']];
const OCCUPATIONS = ['Business', 'Service', 'Homemaker', 'Student', 'Engineer', 'Teacher', 'Retired', 'Self-employed', 'Doctor', 'Accountant', 'Farmer', 'Shop owner'];
const COMPLAINTS = {
  'General Medicine': ['Fever since 2 days with body ache', 'Cough and cold for 4 days', 'Acidity and burning in stomach', 'Loose motions since yesterday', 'Headache and weakness', 'Follow-up for sugar control', 'BP check-up', 'Burning micturition since 3 days', 'Fatigue and hair fall'],
  Cardiology: ['Chest heaviness on exertion', 'Palpitations', 'BP not controlled', 'Breathlessness on climbing stairs', 'Routine cardiac follow-up'],
  Orthopedics: ['Low back pain since 1 week', 'Knee pain while climbing stairs', 'Neck pain radiating to shoulder', 'Twisted ankle while walking', 'Shoulder stiffness'],
  Pediatrics: ['Fever and cold in child', 'Loose motions in child since 1 day', 'Vaccination visit', 'Poor appetite', 'Cough with wheeze'],
  Dermatology: ['Pimples on face', 'Itchy rash on body', 'Ring-shaped itchy patches', 'Dandruff and itchy scalp', 'Hives after eating'],
  Gynecology: ['Painful periods', 'Irregular periods', 'Routine ANC check-up', 'White discharge', 'Heavy bleeding during periods'],
  ENT: ['Sore throat and difficulty swallowing', 'Ear pain since 2 days', 'Sneezing and blocked nose', 'Giddiness', 'Nasal blockage and headache'],
};
const DX_BY_DEPT = {
  'General Medicine': ['Fever, unspecified', 'Acute upper respiratory infection (URTI)', 'Acute gastritis', 'Acute gastroenteritis', 'Type 2 diabetes mellitus without complications', 'Essential (primary) hypertension', 'Urinary tract infection', 'Headache', 'Hypothyroidism', 'Anaemia, unspecified', 'Gastro-oesophageal reflux disease', 'Acute bronchitis'],
  Cardiology: ['Essential (primary) hypertension', 'Dyslipidaemia', 'Coronary artery disease', 'Angina pectoris', 'Chest pain, unspecified'],
  Orthopedics: ['Low back pain', 'Osteoarthritis of knee', 'Cervicalgia', 'Sprain of ankle', 'Adhesive capsulitis of shoulder', 'Myalgia'],
  Pediatrics: ['Fever, unspecified', 'Viral gastroenteritis (child)', 'Routine child health examination', 'Acute upper respiratory infection (URTI)', 'Acute bronchiolitis'],
  Dermatology: ['Acne vulgaris', 'Tinea corporis', 'Urticaria', 'Seborrhoeic dermatitis', 'Atopic dermatitis'],
  Gynecology: ['Dysmenorrhoea', 'Polycystic ovarian syndrome', 'Supervision of normal pregnancy', 'Acute vaginitis', 'Menorrhagia'],
  ENT: ['Acute pharyngitis', 'Otitis media', 'Allergic rhinitis', 'Vertigo / dizziness', 'Chronic sinusitis', 'Acute tonsillitis'],
};

module.exports = { DEPARTMENTS, DOCTORS, DIAGNOSES, MEDICINES, TEMPLATES, LAB_TESTS, WARDS, SUPPLIERS, INVENTORY_ITEMS, FIRST, LAST, AREAS, OCCUPATIONS, COMPLAINTS, DX_BY_DEPT };
